name: Conditional Jobs Flow

on:
  workflow_dispatch:
    inputs:
      jobs_to_run:
        description: "Enter the jobs to run (comma separated). Options: job1, job2, job3"
        required: true
        default: "job1"  # Change the default if needed

jobs:
  job1:
    runs-on: ubuntu-latest
    # job1 should always run if any of the jobs that call it is selected
    if: contains(github.event.inputs.jobs_to_run, 'job1')
    steps:
      - name: Run Job 1
        run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # if there's a dependency on job1
    if: contains(github.event.inputs.jobs_to_run, 'job2')
    steps:
      - name: Run Job 2
        run: echo "Running Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job1  # if there's a dependency on job1
    if: contains(github.event.inputs.jobs_to_run, 'job3')
    steps:
      - name: Run Job 3
        run: echo "Running Job 3"
