name: CI

on:
  workflow_dispatch:
    inputs:
      run_job1:
        type: boolean
        description: 'Run Job 2?'
        default: true
      run_job2:
        type: boolean
        description: 'Run Job 2?'
        default: false
      run_job3:
        type: boolean
        description: 'Run Job 3?'
        default: false

jobs:
  job1:
    runs-on: ubuntu-latest
    # This job runs if either job2 or job3 is selected.
    if: github.event.inputs.run_job2 == 'true' || github.event.inputs.run_job3 == 'true'
    
    steps:
      - name: Run Job 1
        run: echo "Running Job 1 because a dependent job was selected."

  job2:
    runs-on: ubuntu-latest
    needs: job1
    # This job runs only if the 'run_job2' checkbox was ticked.
    if: github.event.inputs.run_job2 == 'true'
    steps:
      - name: Run Job 2
        run: echo "Running Job 2"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    # This job runs only if the 'run_job3' checkbox was ticked.
    if: github.event.inputs.run_job3 == 'true'
    steps:
      - name: Run Job 3
        run: echo "Running Job 3"
